---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-microservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bluecompute
        tier: backend
        micro: auth
    spec:
      containers:
      - name: auth-service
        image: registry.ng.bluemix.net/chrisking/us-micro-auth:jkwong-dev
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /opt/hs256-key
          name: hs256-key
        ports:
        - containerPort: 8080
      volumes:
      - name: hs256-key
        secret:
          defaultMode: 420
          secretName: hs256-key
---        
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: bluecompute
    tier: backend
    micro: auth
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: bluecompute
    tier: backend
    micro: auth
...
